"""
core/assembler.py — scene.py code assembler
=============================================
Takes the normalised config dict from loader.py and writes a complete,
runnable Manim Python file.

HOW IT WORKS
------------
1. Write the file header  (docstring + imports + brand constants + helpers)
2. Open the class definition  (class SceneName(MovingCameraScene):)
3. Open construct()
4. For each beat (in time order):
   a. Write a beat comment block
   b. Write the beat wait/hold if there is a gap from the previous beat
   c. Instantiate each declared primitive and call .render()
      — render() returns a string of indented Manim code
   d. Write the transition
5. Write the final fade to black
6. Close construct() and class
7. Write the if __name__ == "__main__": pass footer

OUTPUT FORMAT
-------------
The generated scene.py is self-contained — it imports only from manim
and numpy. It does NOT import from this tool. This means:
  - It can be moved to any Manim project folder and rendered
  - It has no dependency on origeno/ being on PYTHONPATH
  - All brand constants are inlined as literals

INDENTATION
-----------
All primitive render() methods return code with 8 spaces of indentation
(2 levels: class body + construct body). The assembler writes beat
comment blocks at 8 spaces. Class definition is at 0 spaces.

ADDING A BEAT-LEVEL FEATURE
----------------------------
If you need to add logic at the beat level (e.g. a new camera move type),
add it to _write_beat() below, not to individual primitives.
"""

from __future__ import annotations
from pathlib import Path
from core.registry import get as get_primitive
from defaults import PALETTE, BACKGROUND, FONT


# ── Indentation constants ────────────────────────────────────────────────────
I2 = "        "   # 8 spaces — inside construct()
I1 = "    "       # 4 spaces — inside class body


def assemble(config: dict, output_path: str | Path) -> Path:
    """
    Generate a scene.py file from a validated config dict.

    Parameters
    ----------
    config      : dict returned by loader.load()
    output_path : where to write the .py file

    Returns
    -------
    Path to the written file.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []

    _write_header(lines, config)
    _write_class_open(lines, config)
    _write_construct_open(lines, config)
    _write_circuit_bg(lines)

    for beat in config["beats"]:
        _write_beat(lines, beat, config)

    _write_outro(lines, config)
    _write_footer(lines, config)

    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return output_path


# ── Header ───────────────────────────────────────────────────────────────────

def _write_header(lines: list, config: dict) -> None:
    s = config["scene"]
    c = config["config"]
    render_flag = {
        "preview": "-pql",
        "1080p"  : "-pqh",
        "4k"     : "-pqk",
    }.get(c["resolution"], "-pqh")

    lines += [
        f'"""',
        f'{s["output"]} — Origeno',
        f'{"─" * 40}',
        f'Scene  : {s["name"]}',
        f'Class  : {s["class"]}',
        f'Duration: {s["duration"]}s',
        f'',
        f'RENDER:',
        f'  manim {render_flag} {s["output"]} {s["class"]}',
        f'',
        f'AUTO-GENERATED by Origeno tool. Do not edit by hand.',
        f'To change this scene, edit the .toml config and re-run:',
        f'  python origeno.py <config.toml>',
        f'"""',
        f'',
        f'from manim import *',
        f'import numpy as np',
        f'',
    ]

    # Inline brand constants (so scene.py is self-contained)
    lines.append("# ── Brand constants ────────────────────────────────────────────────────────")
    bg = c.get("background", BACKGROUND)
    lines.append(f'C_BG    = "{bg}"')
    pal = c.get("palette", PALETTE)
    for name, hex_val in pal.items():
        cname = f"C_{name.upper()}"
        lines.append(f'{cname:<12} = "{hex_val}"')
    lines += [
        f'C_WHITE  = "{pal.get("WHITE", "#EEEBE3")}"',
        f'C_DARK   = "{pal.get("DARK",  "#1C1A14")}"',
        f'C_DIM    = "{pal.get("DIM",   "#888070")}"',
        f'C_GRID   = "{pal.get("GRID",  "#C8C0A8")}"',
        f'FONT     = "{FONT}"',
        f'',
    ]

    # Helper functions
    lines += [
        "# ── Text helpers ────────────────────────────────────────────────────────────",
        "def H1(text, color=None, size=44):",
        f'    color = color or C_WHITE',
        f'    return Text(text, font=FONT, color=color, font_size=size, weight=BOLD)',
        f'',
        "def TAG(text, color=None, size=15):",
        f'    color = color or C_DIM',
        f'    return Text(text, font=FONT, color=color, font_size=size)',
        f'',
        "def STAT(text, color=None, size=56):",
        f'    color = color or C_RED',
        f'    return Text(text, font=FONT, color=color, font_size=size, weight=BOLD)',
        f'',
        "# ── Animation helpers ───────────────────────────────────────────────────────",
        "def ripple(scene, center, color=None, n=3, base_r=0.5, run_t=0.7):",
        '    color = color or C_CYAN',
        '    rings = [Circle(radius=base_r*(i+1)*0.6, color=color,',
        '                    stroke_width=max(0.5, 2.5-i*0.5),',
        '                    stroke_opacity=max(0, 0.7-i*0.2)).move_to(center)',
        '             for i in range(n)]',
        '    scene.play(LaggedStart(*[',
        '        r.animate(run_time=run_t).scale(2.2).set_stroke(opacity=0)',
        '        for r in rings], lag_ratio=0.18))',
        f'',
        "def slam_in(scene, mob, bounces=3, run_t=0.6):",
        '    mob.scale(0.01)',
        '    scene.play(mob.animate(run_time=run_t, rate_func=bounce).scale(100))',
        f'',
        "def circuit_bg(scene):",
        '    dots = VGroup()',
        '    for x in np.arange(-7, 7.5, 1.4):',
        '        for y in np.arange(-4, 4.5, 1.4):',
        '            d = Dot(point=[x, y, 0], radius=0.03,',
        '                    color=C_GRID, fill_opacity=0.5)',
        '            dots.add(d)',
        '    scene.add(dots)',
        '    return dots',
        f'',
        f'',
    ]


# ── Class and construct ───────────────────────────────────────────────────────

def _write_class_open(lines: list, config: dict) -> None:
    s = config["scene"]
    lines += [
        f'class {s["class"]}(MovingCameraScene):',
        f'',
    ]


def _write_construct_open(lines: list, config: dict) -> None:
    lines += [
        f'{I1}def construct(self):',
        f'{I2}# ── Timing constants (seconds per beat) ────────────────────────────────────',
    ]
    for beat in config["beats"]:
        bid = beat["id"]
        dur = beat["time_end"] - beat["time_start"]
        lines.append(f'{I2}T_BEAT_{bid:<3} = {dur:.1f}   # "{beat.get("name", "")}"')
    lines += [
        f'',
        f'{I2}self.camera.background_color = C_BG',
        f'{I2}self.camera.frame.save_state()',
        f'',
    ]


def _write_circuit_bg(lines: list) -> None:
    lines += [
        f'{I2}# ── Background ─────────────────────────────────────────────────────────────',
        f'{I2}_bg = circuit_bg(self)',
        f'{I2}all_objects = VGroup()   # track everything for final fade',
        f'',
    ]


# ── Beat rendering ───────────────────────────────────────────────────────────

def _write_beat(lines: list, beat: dict, config: dict) -> None:
    bid  = beat["id"]
    name = beat.get("name", f"Beat {bid}")
    dur  = beat["time_end"] - beat["time_start"]

    lines += [
        f'{I2}# {"═" * 66}',
        f'{I2}# BEAT {bid} — {name}',
        f'{I2}# Time: {beat["time_start"]}s → {beat["time_end"]}s  ({dur:.1f}s)',
    ]
    if beat.get("narration"):
        narration = beat["narration"]
        lines.append(f'{I2}# Narration: "{narration}"')
    lines.append(f'{I2}# {"═" * 66}')
    lines.append(f'')

    # On-screen text (if any and no primitive handles it)
    if beat.get("on_screen_text") and "stamp" not in beat["primitives"]:
        txt = beat["on_screen_text"].replace('"', '\\"')
        lines += [
            f'{I2}_txt_{bid} = H1("{txt}", color=C_WHITE)',
            f'{I2}self.play(FadeIn(_txt_{bid}), run_time=0.6)',
            f'{I2}all_objects.add(_txt_{bid})',
            f'',
        ]

    # Camera move in
    _write_camera_in(lines, beat, bid)

    # Ken Burns
    if beat.get("ken_burns"):
        _write_ken_burns(lines, beat["ken_burns"], bid)

    # Primitives — render each declared one
    for prim_name, prim_config in beat["primitives"].items():
        try:
            cls = get_primitive(prim_name)
        except KeyError as e:
            lines.append(f'{I2}# WARNING: {e}')
            continue

        obj = cls(prim_config, config, beat)
        code = obj.render()
        # Dedent the primitive's code block (remove common leading whitespace)
        # then re-indent to construct() level (8 spaces).
        import textwrap
        code = textwrap.dedent(code)
        for line in code.splitlines():
            if line.strip() == "":
                lines.append("")
            else:
                lines.append(f'{I2}{line}')
        lines.append(f'')

    # Hold for beat duration
    lines += [
        f'{I2}self.wait(T_BEAT_{bid})',
        f'',
    ]

    # Transition out
    _write_transition(lines, beat, bid)


def _write_camera_in(lines: list, beat: dict, bid: int) -> None:
    cam = beat.get("camera", "static")
    if cam == "static":
        return
    moves = {
        "zoom-in"  : "self.camera.frame.animate.scale(0.7)",
        "zoom-out" : "self.camera.frame.animate.scale(1.3)",
        "pan-left" : "self.camera.frame.animate.shift(LEFT * 2)",
        "pan-right": "self.camera.frame.animate.shift(RIGHT * 2)",
    }
    if cam in moves:
        lines += [
            f'{I2}# Camera: {cam}',
            f'{I2}self.play({moves[cam]}, run_time=0.8)',
            f'',
        ]


def _write_ken_burns(lines: list, kb: str, bid: int) -> None:
    moves = {
        "zoom-in"  : "self.camera.frame.animate.scale(0.82)",
        "zoom-out" : "self.camera.frame.animate.scale(1.15)",
        "pan-left" : "self.camera.frame.animate.shift(LEFT * 1.5)",
        "pan-right": "self.camera.frame.animate.shift(RIGHT * 1.5)",
    }
    if kb in moves:
        lines += [
            f'{I2}# Ken Burns: {kb}',
            f'{I2}self.play({moves[kb]}, run_time=1.2, rate_func=smooth)',
            f'',
        ]


def _write_transition(lines: list, beat: dict, bid: int) -> None:
    tr = beat.get("transition", "fade")
    if tr == "keep":
        lines += [
            f'{I2}# Transition: keep — objects persist into next beat',
            f'',
        ]
    elif tr == "fade":
        lines += [
            f'{I2}# Transition: fade',
            f'{I2}_fade_targets = [m for m in self.mobjects',
            f'{I2}                 if m is not _bg and isinstance(m, VMobject)]',
            f'{I2}if _fade_targets:',
            f'{I2}    self.play(FadeOut(VGroup(*_fade_targets)), run_time=0.5)',
            f'{I2}self.camera.frame.restore()',
            f'',
        ]
    elif tr == "cut":
        lines += [
            f'{I2}# Transition: cut',
            f'{I2}self.remove(*[m for m in self.mobjects if m is not _bg])',
            f'{I2}self.camera.frame.restore()',
            f'',
        ]
    elif tr in ("fade-to-black", "slide"):
        # handled in _write_outro
        pass


def _write_outro(lines: list, config: dict) -> None:
    lines += [
        f'{I2}# ── Final fade to black ──────────────────────────────────────────────────────',
        f'{I2}_outro_targets = [m for m in self.mobjects if isinstance(m, VMobject)]',
        f'{I2}if _outro_targets:',
        f'{I2}    self.play(*[FadeOut(m) for m in _outro_targets], run_time=1.2)',
        f'{I2}self.wait(0.5)',
        f'',
    ]


def _write_footer(lines: list, config: dict) -> None:
    s = config["scene"]
    lines += [
        f'',
        f'if __name__ == "__main__":',
        f'    pass',
        f'',
        f'# ── End of {s["output"]} ──',
    ]